feat(rpc): add cancellation param to submit_block rpc
ralexstokes/mev-rs pull request #119
Opened 2023-08-24 03:08 UTC by PatStiles

reopening #115

2023-08-24 03:09 UTC, PatStiles commented
@ralexstokes

2023-08-29 02:03 UTC, ralexstokes commented on mev-rs/src/blinded_block_relayer/api/client.rs
> +        if with_cancellations { request = request.query(&[("cancellations", with_cancellations)])};
it looks like the api takes the value `1` instead of the boolean `true`

ref:
https://flashbots.github.io/relay-specs/#/Builder/submitBlock

2023-09-13 05:03 UTC, PatStiles commented
Will address and reopen after rebase

2023-09-13 14:45 UTC, ralexstokes requested changes
looks like the merge was a bit off and it looks like you are replaying part of the `main` branch on top of your commit (which is repeated?)

you should be able to just cherry-pick the one commit off of some recent commit from `main` and work from there

2023-09-13 21:21 UTC, PatStiles commented
Closing in favor of #131

2023-09-13 21:21 UTC, closed without merging