feat: support holesky
ralexstokes/mev-rs pull request #120
Opened 2023-08-25 16:30 UTC by chirag-bgh

Closes #118

2023-09-11 15:19 UTC, ralexstokes requested changes
nice updates

2023-09-11 15:19 UTC, ralexstokes commented on mev-boost-rs/src/service.rs
> +        let clock = context.clock().unwrap();
we shouldn't just blindly `unwrap` things unless we know they won't panic

here's how I'm thinking about this right now:

https://github.com/ralexstokes/mev-rs/pull/124#discussion_r1319987479

2023-09-11 15:19 UTC, ralexstokes commented on mev-build-rs/src/service.rs
> +        let current_epoch = clock.clone().current_epoch().expect("after genesis");
you shouldn't need to `clone` here...

2023-09-11 20:14 UTC, ralexstokes requested changes
a few more things to update

2023-09-11 20:14 UTC, ralexstokes commented on mev-relay-rs/src/service.rs
> +        let clock = context.clock().unwrap();
same thing here on the clock

2023-09-11 20:14 UTC, ralexstokes commented on mev-rs/src/validator_registry.rs
> +        current_timestamp: u128,
we should actually leave this as `u64` and if the caller is providing `u128` lets do the conversion once at that call site

2023-09-12 15:43 UTC, ralexstokes approved these changes
great! nice and simple :)

can you rebase all of the commit here to just a single commit w/ the final changes?

then I'll merge

2023-09-12 16:21 UTC, chirag-bgh commented
> great! nice and simple :)
> 
> can you rebase all of the commits here to just a single commit w/ the final changes?
> 
> then I'll merge

Done

2023-09-13 14:41 UTC, merged