Change parameters to explicitly pass in `genesis_validators_root` and `context`
ralexstokes/mev-rs pull request #213
Opened 2024-03-15 21:31 UTC by EchoAlice

2024-03-16 15:29 UTC, ralexstokes requested changes
let's use the `Root` type instead of `Node` and also you'll need to rebase from `main`

2024-03-16 15:29 UTC, ralexstokes commented on mev-relay-rs/src/relay.rs
> +    genesis_validators_root: &Node,
```suggestion
    genesis_validators_root: &Root,
```

2024-03-16 15:29 UTC, ralexstokes commented on mev-relay-rs/src/relay.rs
> +    ssz::prelude::{Merkleized, Node},
let's just use `Root` below

2024-03-18 16:09 UTC, EchoAlice commented on mev-relay-rs/src/relay.rs
> +    genesis_validators_root: &Node,
Soooo picky... 👀 😴

2024-03-26 17:09 UTC, ralexstokes approved these changes
looks good!

2024-03-26 17:10 UTC, merged