Add Checking of Bid Public Keys
ralexstokes/mev-rs pull request #90
Opened 2023-02-28 23:33 UTC by PatStiles

WIP for  #82 . 

- [x] Extends Relay Client to tracks BlsPublicKeys
- [x] Checks that a Relays BlsPublicKey matches SignedBuilder BlsPublicKey
- [ ] Parses BlsPublicKey from Relay Mux config

2023-03-01 00:35 UTC, ralexstokes requested changes
nice start! I left some comments to iterate the code so we end up with better encapsulation of all the details of handling relay data

2023-03-01 00:35 UTC, ralexstokes commented on mev-boost-rs/src/relay_mux.rs
> +                        if let Err(err) = validate_bid(&mut bid, &self.context) {
better to encapsulate this inside `validate_bid`

just pass the `&self.relays[relay_index]` as another parameter to `validate_bid` and check there

2023-03-01 00:35 UTC, ralexstokes commented on mev-boost-rs/src/relay_mux.rs
> +    fn test_bid_verification() {}
remove this unless you want to add a test -- which would be great!

2023-03-01 00:35 UTC, ralexstokes commented on mev-boost-rs/src/relay_mux.rs
> +            return Err(Error::NoBids);
is from the nightly cargo fmt?

try `just fmt` from the repo root dir to see if it stays

2023-03-01 00:35 UTC, ralexstokes commented on mev-boost-rs/src/service.rs
> +            return relay_mux;
same thing on formatting change here

2023-03-01 00:35 UTC, ralexstokes commented on mev-boost-rs/src/service.rs
> +    relays: Vec<(Url, BlsPublicKey)>,
at this point I'd move to encapsulate these details behind a `Relay` type

I'd do this:

1) add `relay.rs` along with a `mod relay;` in the `lib.rs`
2) define something like:
```rust
pub struct Relay {
    api: BlindedBlockProviderClient,
    public_key: BlsPublicKey,
}
```
3. parse the config `Strings` as URLs, make a client for each URL, parse the public key from the URL's `hostname` and then use some combo of `hex::decode` and `BlsPublicKey::try_from(_: &[u8])` to get a key; provide the client and the key as inputs to a `Relay::new`

2023-03-01 00:35 UTC, ralexstokes commented on mev-boost-rs/src/service.rs
> +    pub public_keys: Vec<String>,
the format has the public key _in_ the URL which is already provided in the `relays` entry to this config; so we can remove this -- see the comment below about a way to grab the keys from the URLs themselves while making `Relay` instances

2023-03-10 18:37 UTC, PatStiles commented
resolves #82

2023-03-31 06:00 UTC, ralexstokes requested changes
nice work! left some comments/suggestions for how to move forward

2023-06-03 01:11 UTC, ralexstokes commented
fixed in #96, closing as stale, thank you for the effort here!

2023-06-03 01:11 UTC, closed without merging